name: network_bound_http
description: "A new Flutter plugin project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.10.7
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  network_bound_http_platform_interface:
    path: ../network_bound_http_platform_interface
  network_bound_http_android:
    path: ../network_bound_http_android
  uuid: ^4.5.2
  path_provider: ^2.1.5
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  collection: ^1.19.1

flutter:
  plugin:
    platforms:
      android:
        default_package: network_bound_http_android

