name: network_bound_http
description: A Flutter/Dart library for network requests with selectable network type (Wi-Fi, cellular, or standard).
version: 0.1.0
homepage: https://github.com/giulitu95/network_bound_http/tree/v0.1.0/network_bound_http
license: MIT
publish_to: "https://pub.dev"

environment:
  sdk: ^3.10.7
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  network_bound_http_platform_interface:
    path: ../network_bound_http_platform_interface
  network_bound_http_android:
    path: ../network_bound_http_android
  uuid: ^4.5.2
  path_provider: ^2.1.5
  path: ^1.9.1
  equatable: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  collection: ^1.19.1
  lcov_parser: ^0.1.2
  path_provider_platform_interface: ^2.1.2

flutter:
  plugin:
    platforms:
      android:
        default_package: network_bound_http_android

