name: network_bound_http_platform_interface
description: Defines the shared platform interface for network_bound_http.
homepage: https://github.com/giulitu95/network_bound_http/tree/v0.1.0/network_bound_http_platform_interface
version: 0.1.0
licence: MIT
publish_to: "https://pub.dev"

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.0
  uuid: ^4.5.2

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
