name: Android Tests & Coverage

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Test & Coverage
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '21'

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3
      with:
        api-level: 36
        build-tools: 36.0.0

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.38.6' 

    - name: Show local.properties for debug
      working-directory: ./network_bound_http_android/example
      run: flutter pub get

    - name: Generate local.properties
      working-directory: ./network_bound_http_android/example/android
      run: |
        echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
        echo "flutter.sdk=$FLUTTER_ROOT" >> local.properties
        
    - name: Show local.properties for debug
      working-directory: ./network_bound_http_android/example/android
      run: cat local.properties


    - name: Generate gradle wrapper
      working-directory: ./network_bound_http_android/example/android
      run: gradle wrapper --gradle-version 8.14.4

    - name: Grant execute permission for gradlew
      run: chmod +x network_bound_http_android/example/android/gradlew

    - name: Run tests and generate JaCoCo report
      working-directory: ./network_bound_http_android/example/android
      run: ./gradlew jacocoTestReport

    - name: Upload JaCoCo XML coverage
      uses: actions/upload-artifact@v4
      with:
        name: jacoco-coverage-xml
        path: network_bound_http_android/example/build/network_bound_http_android/reports/jacoco/jacocoTestReport-coverage.xml

