name: Network Bound Http

on:
  push:

jobs:
  network-bound-http-flutter-format:                  
    runs-on: ubuntu-latest  

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
            channel: stable
            cache: true

      - run: flutter clean
        working-directory: network_bound_http

      - run: flutter pub get
        working-directory: network_bound_http
          
      - run: dart format --set-exit-if-changed -o none lib test
        working-directory: network_bound_http

  network-bound-http-flutter-analyze:                  
    runs-on: ubuntu-latest  

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
        
      - run: flutter clean
        working-directory: network_bound_http
      
      - run: flutter pub get
        working-directory: network_bound_http

      - run: flutter analyze
        working-directory: network_bound_http

  network-bound-http-flutter-test:                  
    runs-on: ubuntu-latest  

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      
      - name: Flutter clean
        run: flutter clean
        working-directory: network_bound_http

      - name: Get dependencies
        run: flutter pub get
        working-directory: network_bound_http
          
      - name: Launch flutter test
        run: flutter test --machine --coverage 
        working-directory: network_bound_http

      - name: Upload to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: network_bound_http/coverage/lcov.info
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}

  network-bound-http-android-flutter-format:                  
    runs-on: ubuntu-latest  

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
            channel: stable
            cache: true

      - run: flutter clean
        working-directory: network_bound_http_android

      - run: flutter pub get
        working-directory: network_bound_http_android
          
      - run: dart format --set-exit-if-changed -o none lib test
        working-directory: network_bound_http_android

  network-bound-http-android-flutter-analyze:                  
    runs-on: ubuntu-latest  

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
        
      - run: flutter clean
        working-directory: network_bound_http_android
      
      - run: flutter pub get
        working-directory: network_bound_http_android

      - run: flutter analyze
        working-directory: network_bound_http_android

  network-bound-http-platform-interface-flutter-format:                  
    runs-on: ubuntu-latest  

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
            channel: stable
            cache: true

      - run: flutter clean
        working-directory: network_bound_http_platform_interface

      - run: flutter pub get
        working-directory: network_bound_http_platform_interface
          
      - run: dart format --set-exit-if-changed -o none lib test
        working-directory: network_bound_http_platform_interface

  network-bound-http-platform-interface-flutter-analyze:                  
    runs-on: ubuntu-latest  

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
        
      - run: flutter clean
        working-directory: network_bound_http_platform_interface
      
      - run: flutter pub get
        working-directory: network_bound_http_platform_interface

      - run: flutter analyze
        working-directory: network_bound_http_platform_interface