name: network_bound_http_android
description: Android implementation of network_bound_http supporting network selection.
version: 0.1.0
homepage: https://github.com/giulitu95/network_bound_http/tree/v0.1.0/network_bound_http_android
licence: MIT
publish_to: "https://pub.dev"


environment:
  sdk: ^3.10.7
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  network_bound_http_platform_interface:
    path: ../network_bound_http_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.faespa.network_bound_http_android
        pluginClass: NetworkBoundHttpAndroidPlugin
        dartPluginClass: NetworkBoundHttpAndroid

